runtime: nodejs
vm: true

env_variables:
  # --REQUIRED--
  DATABASE_URI: 'mongodb://JustinDMoore:Ju$tin!1@ds013222.mlab.com:13222/corpboard'
  APP_ID: <wx8eMIWy1f9e60WrQJYUI81jlk5g6YYAPPmwxequ>
  MASTER_KEY: <ghQaWz8I6ufa4jd5ZEN3W6kTAOXMSBCt6r9k7gKt>
  # --OPTIONAL--
  FILE_KEY: <'57edad47-342b-49b5-97c5-bd384b2b8c46'>
  # PARSE_MOUNT: /parse
  # CLOUD_CODE_MAIN:  